#!/command/with-contenv sh

if [ "$LEGO_ARGS" != "daemon" ]; then
    echo "[Lego] Not in daemon mode. Skipping crond service."
    exit 0
fi

echo "[Lego] Daemon mode detected. Starting crond..."
exec crond -f -l 2
